### ISSUE TITLE
Determining the value of CLUSTER_N

### ISSUE THREAD

**Issue by yfu** [shendurelab/LACHESIS#14]
For a genome with an unknown number of chromosomes (we have not karyotyped it yet), it there a good way to determine the number of chromosomes using Hi-C data? I tried to do some simple hierarchical clustering using the data points in `heatmap.txt`, but I cannot find obvious turning points... Does `LACHESIS` produce some results that can help one determine the number of chromosomes? Thanks!

**Comment by JingaJenga** [comment]
The short answer is - No, you can't reliably infer chromosome number.  You can get a rough estimate but not a precise one.  For more details, see Supplementary Fig. 13 in the Nature Biotech paper (and the paragraph in the Discussion that refers to it.)
