### ISSUE TITLE
 get a very big clusters

### ISSUE THREAD

**Issue by liufuyan2016** [shendurelab/LACHESIS#22]
I have  recently used LACHESIS for  the long read assemblies(the assembly contig N50 10Mb). I get a very big clusters(60Mb,50% genome) no matter what the parameter adjusted. Could you help me?

**Comment by tangerzhang** [comment]
Hi liufuyan2016,
Have you solve your problem?
I am having the same problem when using LACHESIS for HiC scaffolding.
I got actually two very very big clusters (500M).
I re-open this issue as I have no idea how to solve this.
Could any one help me with this issue?
Thanks!

**Comment by kfletcher88** [comment]
Hi, I know this is nearly two years old, but do you guys have a solution for this?
I was thinking to down-sample the data to see if that increases the number of large clusters. At the moment I am obtaining 99.58% of the assembly in a single cluster.
Thanks

**Comment by tangerzhang** [comment]
The solution is to use 3D-DNA pipeline to correct the mis-joint contigs.
