### ISSUE TITLE
null_score != 0

### ISSUE THREAD

**Issue by ivyhzau** [shendurelab/LACHESIS#24]
Hi,
It run correctly at first, then it showed some messasge and Lachesis stoped. The message are as follows, and I don't know how to solve it.

Reinserting 14 shreds
OrientContigs
ContigOrdering with 2 contigs used (17 unused):	0_fw,3_fw
Full ordering:	Order contains 2 of 19 contigs (10.526316%), with a total length of 379396 of 1399223 (27.114763%).
Lachesis: ChromLinkMatrix.cc:739: double ChromLinkMatrix::EnrichmentScore(const ContigOrdering&) const: Assertion `null_score != 0' failed.
Aborted (core dumped)

Thanks.
ivy

**Comment by kfletcher88** [comment]
Hi, did you find a solution for this?

**Comment by Epigenetics-Wang** [comment]
Hi,@ivyhzau 
Did you solve the problem you mentioned? I have the same trouble.
