### ISSUE TITLE
./configure checking samtools... failed

### ISSUE THREAD

**Issue by winni-liu** [shendurelab/LACHESIS#47]
I configure by this code
`./configure --with-samtools=/psd/biosoft/samtools_suit/samtools-0.1.19/  --with-boost=/psd/biosoft/boost_1_60_0_b1/` 
but I get the error messages ：

**......................
checking if samtools is wanted... yes
checking sam.h usability... yes
checking sam.h presence... yes
checking for sam.h... yes
checking for sam_open in -lbam... no
checking samtools... failed
configure: error: either specify a valid samtools installation with --with-samtools=DIR or disable samtools usage with --without-samtools**

also, I have tested other way and configure:
**export LACHESIS_BOOST_DIR="/psd/biosoft/boost_1_60_0_b1/:$LACHESIS_BOOST_DIR"
export LACHESIS_SAMTOOLS_DIR="/psd/biosoft/samtools_suit/samtools-0.1.19/:$LACHESIS_SAMTOOLS_DIR"**

but it didn't work, Samtools is well installed and available。

**Comment by winni-liu** [comment]
I have changed samtools-1.5 to 0.1.19 and changed the bashrc.
`./configure --prefix=/psd/biosoft/LACHESIS-master --with-samtools=/psd/biosoft/samtools_suit/samtools-0.1.19/`
and I get the same error

**Comment by wenjiexiaomeng** [comment]
Hi,
when i install this, it occurs the same error with u, have u figured out this ?

**Comment by kfletcher88** [comment]
What does your samtools installation directory look like?
I got this to work when all binaries, libraries and executables were in the top directory. This can be obtained with this command:
`git clone git://github.com/samtools/samtools.git `

The install didn't work when they were in sub-directories (e.g. bin and lib).

Hope it helps!

**Comment by winni-liu** [comment]
> Hi,
> when i install this, it occurs the same error with u, have u figured out this ?

I installed the software by conda.

**Comment by winni-liu** [comment]
> What does your samtools installation directory look like?
> I got this to work when all binaries, libraries and executables were in the top directory. This can be obtained with this command:
> `git clone git://github.com/samtools/samtools.git `
> 
> The install didn't work when they were in sub-directories (e.g. bin and lib).
> 
> Hope it helps!

I installed samtools V1.9 in the directory and others error begin.., so I used the conda to install. 
The software was too hard to install

**Comment by fire-activate** [comment]
I configure by this code
./configure --with-samtools=/psd/biosoft/samtools_suit/samtools-0.1.19/ --with-boost=/psd/biosoft/boost_1_60_0_b1/
but I get the error messages ：

......................
checking if samtools is wanted... yes
checking sam.h usability... yes
checking sam.h presence... yes
checking for sam.h... yes
checking for sam_open in -lbam... no
checking samtools... failed
configure: error: either specify a valid samtools installation with --with-samtools=DIR or disable samtools usage with --without-samtools

also, I have tested other way and configure:
export LACHESIS_BOOST_DIR="/psd/biosoft/boost_1_60_0_b1/:$LACHESIS_BOOST_DIR"
export LACHESIS_SAMTOOLS_DIR="/psd/biosoft/samtools_suit/samtools-0.1.19/:$LACHESIS_SAMTOOLS_DIR"
