### ISSUE TITLE
Segmentation fault (core dumped) using reference

### ISSUE THREAD

**Issue by xinwang-bio** [shendurelab/LACHESIS#52]
Hi 
I am scaffolding contigs generated by CANU using Lachesis. I faced a bug “Segmentation fault (core dumped)” when I use the reference (USE_REFERENCE = 1). The bug also existed when I used the test data.
When I don’t use the reference (USE_REFERENCE = 0), it is good for my data and test data. How can I fix it?
Thanks.

**Comment by hzaumsq** [comment]
I met the  same probnelm of you ,Have you sloved it ?

**Comment by xizhesun** [comment]
I met the same probnelm of you ,Have you sloved it ? @hzaumsq  @xinwang-bio
